# Generated by Django 3.0 on 2021-06-06 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Judul buku', max_length=250)),
                ('url_sampul', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13)),
                ('tahun', models.CharField(max_length=5)),
                ('lokasi', models.TextField()),
            ],
            options={
                'ordering': ['judul', 'penulis', 'tahun'],
            },
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama penulis', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='BukuInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3622aae4-345a-4de3-99d9-496f5220c7cf'), primary_key=True, serialize=False)),
                ('batas_waktu', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('k', 'Keluar'), ('t', 'Tersedia'), ('p', 'Perawatan')], default='p', help_text='Ketersediaan Buku', max_length=1)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Buku')),
                ('peminjam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='buku',
            name='penulis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Penulis'),
        ),
    ]
