# Generated by Django 3.0 on 2021-06-06 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukuinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('def2e84b-5e5a-4715-b012-c1d940c1772a'), primary_key=True, serialize=False),
        ),
    ]
