# Generated by Django 3.0 on 2021-06-06 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210606_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukuinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fdc4528e-6917-4729-97cf-d01c6f781562'), primary_key=True, serialize=False),
        ),
    ]
