# Generated by Django 3.0 on 2021-06-06 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210606_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukuinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('32d19c73-2866-4b01-aed0-75de11ba4907'), primary_key=True, serialize=False),
        ),
    ]
