# Generated by Django 3.0 on 2021-06-06 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210606_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukuinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb5c450e-5c77-41bf-808a-9ca4ecda731c'), primary_key=True, serialize=False),
        ),
    ]
