# Generated by Django 3.0 on 2021-06-06 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210606_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukuinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7614f4f-0ec3-4752-9175-c4194159559b'), primary_key=True, serialize=False),
        ),
    ]
