# Generated by Django 3.0 on 2021-06-06 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210606_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukuinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ae918c1-ef74-421f-8269-a4b42715daa4'), primary_key=True, serialize=False),
        ),
    ]
