# Generated by Django 3.0 on 2021-06-28 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210606_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukuinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('138df430-ec0f-4d80-85b7-29ca69357aed'), primary_key=True, serialize=False),
        ),
    ]
