# Generated by Django 3.0 on 2021-06-28 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210628_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukuinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0cebac9b-f77d-4736-8599-8d33e223f03d'), primary_key=True, serialize=False),
        ),
    ]
