# Generated by Django 3.0 on 2021-07-02 16:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210628_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukuinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76e17d00-6e3a-49a5-8d97-91b3c2dc6404'), primary_key=True, serialize=False),
        ),
    ]
